### ISSUE TITLE
프로젝트 구조 설정

### ISSUE THREAD

**Issue by seoyeon0413** [Shopaholism/priceFlow-fastapi-backend-like#3]
Spring Boot New Project 생성: https://start.spring.io/

### 결정사항
- Project
  - Gradle - Groovy
  - Gradle - Kotlin
  - Maven
- Project Metadata
- java version
  - 19
  - 17
  - 11
  - 8
- Dependencies

**Comment by seoyeon0413** [comment]
@parkchanbin54 어떻게 설정하면 좋을지 의견 주세요

**Comment by parkchanbin54** [comment]
- Project
> Maven

- java version
 > 11

- Spring boot version
> 2.7.6

- Dependencies
> Spring Web
> Spring Data JPA
> MySQL Driver
> Lombok
> Spring Cloud
> Spring Boot Dev Tools

**Comment by parkchanbin54** [comment]
@seoyeon0413 우선은 이정도로 픽스하고 진행하고 Dependencies 같은 부분은 필요하면 나중에 pom파일에 추가해서 정리하는 식으로 하는게 어때요?

**Comment by seoyeon0413** [comment]
> @seoyeon0413 우선은 이정도로 픽스하고 진행하고 Dependencies 같은 부분은 필요하면 나중에 pom파일에 추가해서 정리하는 식으로 하는게 어때요?

ok 그렇게해서 프로젝트 생성해보겠습니다.
나머지는 리서치 해보면서 진행해야할거같음

**Comment by parkchanbin54** [comment]
https://github.com/spring-petclinic/spring-petclinic-microservices
MSA구조 참고하시면 됩니다.

**Comment by parkchanbin54** [comment]
https://inpa.tistory.com/entry/GIT-%E2%9A%A1%EF%B8%8F-github-flow-git-flow-%F0%9F%93%88-%EB%B8%8C%EB%9E%9C%EC%B9%98-%EC%A0%84%EB%9E%B5
Branch 구조가 Master, Develop, Feature, Release, Hotfix가 있는데 Master, Develop, Hotfix 세개로 상태 나누어서 관리할까요? 
각자 개발 진행하는 branch는 나누어서 Develop_cb, Develop_sy 이런식으로..?

**Comment by seoyeon0413** [comment]
## branch 전략
- master
- develop
- feature
- hotfix

### develop
msa service 별로 develop 브랜치 따기
(ex) `develop-like`,` develop-user`

### feature
`feature` 브랜치의 source는 `develop`
기능별로 feature 브랜치 따는 느낌
(ex) `develop-user`에서 `feature-user_interface` 브랜치 따서 다시 `develop-user`로 머지

### hotfix
hotfix는 source가 어디든 상관없이 그냥 에러 발생하면 따서 머지하기

### MR
MR은 `master` 브랜치에 머지할때만 올려서 코드리뷰하는 방식

------------

자세한건 리서치해서 브랜치명이나 그런거 코멘트 남기면 됩니다.

**Comment by seoyeon0413** [comment]
> * Project
> 
> > Maven
> 
> * java version
> 
> > 11
> 
> * Spring boot version
> 
> > 2.7.6
> 
> * Dependencies
> 
> > Spring Web
> > Spring Data JPA
> > MySQL Driver
> > Lombok
> > Spring Cloud
> > Spring Boot Dev Tools

Spring Cloud는 관련된거 모두 넣으면 되는거임?
